In [1]:
import numpy as np


# Завдання 1: Одновимірний масив

In [3]:
vector = np.arange(1, 11)
print(f"Одновимірний масив: {vector}")

Одновимірний масив[ 1  2  3  4  5  6  7  8  9 10]:


# Завдання 2: Двовимірний масив 3x3 заповнений нулями

In [4]:
matrix_3x3 = np.zeros((3, 3))
print("Двовимірний масив 3x3, заповнений нулями:\n", matrix_3x3)

Двовимірний масив 3x3, заповнений нулями:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Завдання 3: Масив 5x5, заповнений випадковими цілими числами

In [5]:
matrix_5x5 = np.random.randint(1, 11, size=(5, 5))
print("Масив 5x5, заповнений випадковими цілими числами:\n", matrix_5x5)

Масив 5x5, заповнений випадковими цілими числами:
 [[ 2  2  9  8  2]
 [ 9  5  2  8  2]
 [ 8  7  2  1  7]
 [ 9  5  2  6 10]
 [ 9  9  3  7  9]]


### Завдання 4: Масив 4x4, заповнений випадковими дійсними числами

In [6]:
matrix_4x4 = np.random.random((4, 4))
print("Масив 4x4, заповнений випадковими дійсними числами:\n", matrix_4x4)

Масив 4x4, заповнений випадковими дійсними числами:
 [[0.99684071 0.898288   0.10603898 0.32574238]
 [0.49841951 0.55686897 0.83697287 0.20134633]
 [0.42407746 0.99108409 0.63939418 0.20956552]
 [0.91774603 0.74062432 0.69841476 0.35405341]]


# Завдання 5: Поелементні операції на одновимірних масивах

In [7]:
vector_a = np.random.randint(1, 11, size=5)
vector_b = np.random.randint(1, 11, size=5)
print("Вектор A:", vector_a)
print("Вектор B:", vector_b)
print("Додавання:", vector_a + vector_b)
print("Віднімання:", vector_a - vector_b)
print("Множення:", vector_a * vector_b)

Вектор A: [10 10  4  1  3]
Вектор B: [3 8 5 6 6]
Додавання: [13 18  9  7  9]
Віднімання: [ 7  2 -1 -5 -3]
Множення: [30 80 20  6 18]


# Завдання 6: Скалярний добуток векторів

In [8]:
vector_c = np.random.random(7)
vector_d = np.random.random(7)
scalar_product = np.dot(vector_c, vector_d)
print("Скалярний добуток векторів C і D:", scalar_product)

Скалярний добуток векторів C і D: 1.7938666242418062


# Завдання 7: Множення матриць 2x2 і 2x3

In [9]:
matrix_2x2 = np.random.randint(1, 11, size=(2, 2))
matrix_2x3 = np.random.randint(1, 11, size=(2, 3))
matrix_product = np.dot(matrix_2x2, matrix_2x3)
print("Множення матриць 2x2 і 2x3:\n", matrix_product)

Множення матриць 2x2 і 2x3:
 [[50 45 11]
 [90 85 19]]


# Завдання 8: Обернена матриця 3x3

In [10]:
matrix_3x3_random = np.random.randint(1, 11, size=(3, 3))
inverse_matrix = np.linalg.inv(matrix_3x3_random)
print("Обернена матриця 3x3:\n", inverse_matrix)

Обернена матриця 3x3:
 [[ 0.29007634  0.04580153 -0.28244275]
 [ 0.09160305 -0.03816794  0.06870229]
 [-0.51145038  0.12977099  0.36641221]]


# Завдання 9: Транспонована матриця 4x4

In [11]:
matrix_4x4_random = np.random.random((4, 4))
transposed_matrix = matrix_4x4_random.T
print("Транспонована матриця 4x4:\n", transposed_matrix)

Транспонована матриця 4x4:
 [[0.37113287 0.40682913 0.29545777 0.60231958]
 [0.06287302 0.03639402 0.89091573 0.41200124]
 [0.0431716  0.64508314 0.11051928 0.00688852]
 [0.6291721  0.92636764 0.63316396 0.0791664 ]]


# Завдання 10: Множення матриці 3x4 на вектор

In [12]:
matrix_3x4 = np.random.randint(1, 11, size=(3, 4))
vector_4 = np.random.randint(1, 11, size=4)
matrix_vector_product = np.dot(matrix_3x4, vector_4)
print("Множення матриці 3x4 на вектор 4:\n", matrix_vector_product)

Множення матриці 3x4 на вектор 4:
 [ 89 101 136]


# Завдання 11: Множення матриці 2x3 на вектор

In [13]:
matrix_2x3_float = np.random.random((2, 3))
vector_3_float = np.random.random(3)
matrix_vector_product_float = np.dot(matrix_2x3_float, vector_3_float)
print("Множення матриці 2x3 на вектор 3 (дійсні числа):\n", matrix_vector_product_float)

Множення матриці 2x3 на вектор 3 (дійсні числа):
 [1.18357102 1.15435339]


# Завдання 12: Поелементне множення матриць 2x2

In [14]:
matrix_2x2_a = np.random.randint(1, 11, size=(2, 2))
matrix_2x2_b = np.random.randint(1, 11, size=(2, 2))
elementwise_multiplication = matrix_2x2_a * matrix_2x2_b
print("Поелементне множення матриць 2x2:\n", elementwise_multiplication)

Поелементне множення матриць 2x2:
 [[ 8 20]
 [60  6]]


# Завдання 13: Множення матриць 2x2

In [15]:
matrix_2x2_c = np.random.randint(1, 11, size=(2, 2))
matrix_2x2_d = np.random.randint(1, 11, size=(2, 2))
matrix_product_2x2 = np.dot(matrix_2x2_c, matrix_2x2_d)
print("Множення матриць 2x2:\n", matrix_product_2x2)


Множення матриць 2x2:
 [[60 42]
 [63 54]]


# Завдання 14: Сума елементів матриці 5x5

In [16]:
matrix_5x5_large = np.random.randint(1, 101, size=(5, 5))
sum_elements = np.sum(matrix_5x5_large)
print("Сума елементів матриці 5x5:", sum_elements)

Сума елементів матриці 5x5: 1336


# Завдання 15: Різниця матриць 4x4

In [17]:
matrix_4x4_a = np.random.randint(1, 11, size=(4, 4))
matrix_4x4_b = np.random.randint(1, 11, size=(4, 4))
difference_matrix = matrix_4x4_a - matrix_4x4_b
print("Різниця матриць 4x4:\n", difference_matrix)

Різниця матриць 4x4:
 [[ 1 -1 -3 -6]
 [ 1  2  6  2]
 [ 7 -5  5 -1]
 [-6  0 -1 -1]]


# Завдання 16: Вектор-стовпчик з сумами елементів рядків матриці 3x3

In [18]:
matrix_3x3_sum = np.random.random((3, 3))
column_vector_sum = np.sum(matrix_3x3_sum, axis=1).reshape(-1, 1)
print("Вектор-стовпчик з сумами елементів рядків матриці 3x3:\n", column_vector_sum)

Вектор-стовпчик з сумами елементів рядків матриці 3x3:
 [[1.06231641]
 [0.54661436]
 [1.77777483]]


# Завдання 17: Квадрат матриці 3x4

In [19]:
matrix_3x4_int = np.random.randint(1, 11, size=(3, 4))
squared_matrix = np.square(matrix_3x4_int)
print("Матриця з квадратами чисел 3x4:\n", squared_matrix)

Матриця з квадратами чисел 3x4:
 [[ 25  16   1   9]
 [ 64   9 100  36]
 [ 49 100   1  64]]


# Завдання 18: Квадратні корені елементів вектора

In [20]:
vector_4_large = np.random.randint(1, 51, size=4)
sqrt_vector = np.sqrt(vector_4_large)
print("Квадратні корені елементів вектора:\n", sqrt_vector)

Квадратні корені елементів вектора:
 [3.         5.56776436 5.29150262 2.23606798]


# Додаткові завдання:

# Додаткове завдання 1: Замінити непарні числа на -1

In [21]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
print("Замінені непарні числа в arr на -1:", arr)

Замінені непарні числа в arr на -1: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


# Додаткове завдання 2: Перетворення 1D-масиву на 2D-масив

In [26]:
arr_1d = np.arange(10)
arr_2d = arr_1d.reshape((2, -1))
print("Перетворений 1D-масив на 2D-масив:\n", arr_2d)

Перетворений 1D-масив на 2D-масив:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


# Додаткове завдання 3: Вертикальне складання масивів

In [25]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
vertical_stack = np.vstack((a, b))
print("Вертикально складені масиви:\n", vertical_stack)

Вертикально складені масиви:
 [[4 8]
 [2 2]
 [8 8]
 [1 3]]


# Додаткове завдання 4: Створення шаблону без жорсткого кодування

In [24]:
a = np.array([1, 2, 3])
output = np.hstack((np.repeat(a, 3), np.tile(a, 3)))
print("Шаблон без жорсткого кодування:\n", output)

Шаблон без жорсткого кодування:
 [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


# Додаткове завдання 5: Спільні елементи між a і b

In [23]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
common_elements = np.intersect1d(a, b)
print("Спільні елементи між a і b:", common_elements)

Спільні елементи між a і b: [2 4]


# Додаткове завдання 6: Позиції перших 5 максимальних значень

In [27]:
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
indices_of_max_5 = np.argsort(a)[-5:][::-1]
print("Позиції перших 5 максимальних значень у масиві a:", indices_of_max_5)


Позиції перших 5 максимальних значень у масиві a: [15 10  3  7 18]


# Додаткове завдання 7: Вилучення NaN значень з масиву

In [28]:
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
a_no_nan = a[~np.isnan(a)]
print("Масив без NaN значень:", a_no_nan)

Масив без NaN значень: [1. 2. 3. 5. 6. 7.]


# Додаткове завдання 8: Евклідова відстань між двома масивами

In [30]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
euclidean_distance = np.linalg.norm(a - b)
print("Евклідова відстань між масивами a і b:", euclidean_distance)

Евклідова відстань між масивами a і b: 6.708203932499369


# Додаткове завдання 9: Індекс 5-го повторення числа 1

In [29]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
index_5th_one = np.where(x == 1)[0][4]
print("Індекс 5-го повторення числа 1 у масиві x:", index_5th_one)

Індекс 5-го повторення числа 1 у масиві x: 8


# Додаткове завдання 10: Позначення повторюваних записів у масиві

In [33]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
unique, counts = np.unique(a, return_counts=True)
repeats = np.isin(a, unique[counts > 1])
repeats[np.where(repeats)[0][::2]] = False
print("Позначення повторюваних записів у масиві a:", repeats)

Позначення повторюваних записів у масиві a: [False  True False False  True False False  True False  True]
